on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            bin: ptail
            name: ptail-Linux-x86_64.tar.gz
          - os: macOS-latest
            bin: ptail
            name: ptail-Darwin-x86_64.tar.gz
          - os: windows-latest
            bin: ptail.exe
            name: ptail-Windows-x86_64.zip
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Cache debug build
        uses: actions/cache@v1
        with:
          key: development-${{ matrix.os }}
          path: target/debug
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Cache release build
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/cache@v1
        with:
          key: production-${{ matrix.os }}
          path: target/release
      - name: Build release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          strip target/${{ matrix.target }}/release/${{ matrix.bin }}
          cd target/${{ matrix.target }}/release
          if [[ "${{ matrix.os }}" == "windows-latest" ]]
          then
          7z a ../../../${{ matrix.name }} ${{ matrix.bin }}
          else
          tar czvf ../../../${{ matrix.name }} ${{ matrix.bin }}
          fi
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          files: 'ptail*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
